{{- if and .Values.persistence.enabled (not .Values.persistence.existingPVClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "firely-server.fullname" . }}-claim
  labels:
    app.kubernetes.io/name: {{ include "firely-server.name" . }}
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: {{ include "firely-server.fullname" . }}-storage-volume
{{- end }}