{{- if and .Values.persistence.enabled (not .Values.persistence.existingPVClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "firely-server.fullname" . }}-storage-volume
  # The label is used for matching the exact claim
  labels:
    usage: {{ include "firely-server.fullname" . }}-storage-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: vonk-storage-account-secret
    shareName: vonk-data
    # In case the secret is stored in a different namespace
    #shareNamespace: default
    readOnly: false
{{- end }}